name: HQS CI tests for pure python repos/folders

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  linting:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_linting_pure_python.yml@main
    with: 
      python_folder: "qoqo_qiskit"
      linting_folder: "qoqo_qiskit"

  unittests:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_tests_pure_python.yml@main
    with:
      python_folder: "qoqo_qiskit"
      # Test code coverage of rust core is over 80 percent
      test_code_coverage: true
      # Run tests also on windows runners
      windows: false
      # Run tests also on macos runners
      macos: true